services:
  twcm:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ..:/workspaces/TWCM:cached
    environment:
      WATCHPACK_POLLING: "true"

    command: sleep infinity
